name: GICore
version: '1.0-SNAPSHOT'
main: org.gi.gICore.GICore
api-version: '1.21'
depend: ["GIAPI"]
commands:
  조회:
    description: "소지금액 확인 커맨드"
    aliases: ['info','recent']
    usage: '/조회(info,recent)'
  입금:
    description: "입금 커맨드 관리자 권한"
    permission: gi.manager
    aliases: ['depo']
    usage: '/입금(depo) 이름 금액'
  출금:
    description: '출금 커맨드'
    aliases: ['draw','out']
    usage: '/출금(draw,out) 금액(amount)'
permissions:
  gi.manager:
    default: op
    description: "관리자 권한"